# -*- coding: utf-8 -*-
"""Split train_val_test set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ioDNbgytiVzXKu24CeD86SIiFwSbi9e

# Train_test_split and move file to directories
"""

from google.colab import drive
drive.mount('/content/drive')

import os
base_dir = '/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified'

test_path = '/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/test'
train_path = '/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/train'
val_path = '/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/val'

from natsort import natsorted
import pandas as pd
import glob

natsorted(glob.glob(train_path + "/*.jpeg"))

#train_dir
train = os.path.join(base_dir, 'train') #create train folder
os.mkdir(train)
Normal = os.path.join(train_path, 'Normal') #create Normal folder in train folder
os.mkdir(Normal)
Pneumonia = os.path.join(train_path, 'Pneumonia') #create Pneumonia folder in train folder
os.mkdir(Pneumonia)

#val_dir
val = os.path.join(base_dir, 'val')
os.mkdir(val)
Normal = os.path.join(val_path, 'Normal')
os.mkdir(Normal)
Pneumonia = os.path.join(val_path, 'Pneumonia')
os.mkdir(Pneumonia)

# test_dir
test = os.path.join(base_dir, 'test')
os.mkdir(test)
Normal = os.path.join(test_path, 'Normal')
os.mkdir(Normal)
Pneumonia = os.path.join(test_path, 'Pneumonia')
os.mkdir(Pneumonia)

normal_path = '/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/data/NORMAL';
pneu_path = "/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/data/PNEUMONIA"

import os

# Get the list of all files in directory tree at given path
normal_list = os.listdir(normal_path)
pneu_list = os.listdir(pneu_path)

print("Normal images: ",len(normal_list))
print("Pnenumonia images: ",len(pneu_list))

normal_list = sorted(normal_list)
pneu_list = sorted(pneu_list)

"""## Split normal images"""

import pandas as pd
df = pd.DataFrame(list(zip(normal_list)), 
               columns =['normal_image']) 
df["normal_image"]

df.to_csv("/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/List normal images.csv")

import pandas as pd
image_list = pd.read_csv("/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/List normal images.csv")

from sklearn.model_selection import train_test_split

norm_train, norm_test = train_test_split(image_list["normal_image"].to_frame(),
                               test_size=0.2, 
                               random_state=46,
                               shuffle = True)
print(len(norm_train))
print (len(norm_test))

from sklearn.model_selection import train_test_split

norm_train, norm_val = train_test_split(norm_train, 
                              test_size=0.25, 
                              random_state=46,
                              shuffle = True)

print("train:", len(norm_train))
print("val:", len(norm_val))
print("test:", len(norm_test))

"""## Split pneumonia images"""

import pandas as pd
df = pd.DataFrame(list(zip(pneu_list)), 
               columns =['pneu_image']) 
df["pneu_image"]

df.to_csv("/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/List pneumonia images.csv")

import pandas as pd
image_list = pd.read_csv("/content/drive/My Drive/IU/Pre-thesis/chest_xray - modified/List pneumonia images.csv")

from sklearn.model_selection import train_test_split

pneu_train, pneu_test = train_test_split(image_list["pneu_image"].to_frame(),
                               test_size=0.2, 
                               random_state=46,
                               shuffle = True)

from sklearn.model_selection import train_test_split

pneu_train, pneu_val = train_test_split(pneu_train, 
                              test_size=0.25, 
                              random_state=46,
                              shuffle = True)

print("train:", len(pneu_train))
print("val:", len(pneu_val))
print("test:", len(pneu_test))

"""# Move file to the folder"""

import shutil

norm_train_list = norm_train["normal_image"].tolist()

for i in range(len(norm_train)):
    fname = norm_train_list[i]
    src = normal_path+"/"+fname   
    # destination path to image
    dst = os.path.join(train_path,"Normal",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

pneu_train_list = pneu_train["pneu_image"].tolist()

for i in range(len(pneu_train)):
    fname = pneu_train_list[i]
    src = pneu_path+"/"+fname      
    # destination path to image
    dst = os.path.join(train_path,"Pneumonia",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

norm_test_list = norm_test["normal_image"].tolist()

for i in range(len(norm_test)):
    fname = norm_test_list[i]
    src = normal_path+"/"+fname   
    # destination path to image
    dst = os.path.join(test_path,"Normal",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

pneu_test_list = pneu_test["pneu_image"].tolist()

for i in range(len(pneu_test)):
    fname = pneu_test_list[i]
    src = pneu_path+"/"+fname   
    # destination path to image
    dst = os.path.join(test_path,"Pneumonia",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

norm_val_list = norm_val["normal_image"].tolist()

for i in range(len(norm_val)):
    fname =  norm_val_list[i]
    src =  normal_path+"/"+fname   
    # destination path to image
    dst = os.path.join(val_path,"Normal",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

pneu_val_list = pneu_val["pneu_image"].tolist()

for i in range(len(pneu_val)):
    fname = pneu_val_list[i]
    src = pneu_path+"/"+fname   
    # destination path to image
    dst = os.path.join(val_path,"Pneumonia",fname)
    # copy the image from the source to the destination
    shutil.move(src, dst)

print("Training set: ",len(norm_train_list),"Normal images",";", len(pneu_train_list),"Pneumonia images")
print("Validation set: ",len(norm_val_list), "Normal images",";", len(pneu_val_list), "Pneumonia images")
print("Test set: ",len(norm_test_list), "Normal images",";", len(pneu_test_list), "Pneumonia images")

